import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="gnbWrap">
          <ul>
            <li><Link href="/">HOME</Link> </li>
            <li><Link href="/list">LIST</Link> </li>
            <li><Link href="/cart">CART</Link> </li>
          </ul>
        </div>
      {children}
      </body>
    </html>
  )
}
